kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: redis-master
  namespace: default
  labels:
    name: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
      - name: redis-master
        image: 'redis'
        ports:
        - containerPort: 6379
        - protocol: tcp

