kind: Service
apiVersion: v1
metadata:
  name: redis-master
  namespace: default
  labels:
    name: redis-master
spec:
  selector:
    name: redis-master
  ports:
  - port: 6379
    targetPort: 6379
