# docker build --rm -f Dockerfile.agent -t drone/agent .

# FROM drone/ca-certs
FROM r.crun.top/library/golang:1.8

ENV GODEBUG=netdns=go
ADD dist/coderun-agent /bin/coderun-agent

EXPOSE 3000
HEALTHCHECK CMD ["/bin/coderun-agent", "ping"]

ENTRYPOINT ["/bin/coderun-agent"]
